import type {
  AdminStats,
  CaretakerStats,
  CustomerStats,
  CourierStats,
  Booking,
  Cage,
  Payment,
  DailyReport,
  DeliveryTask,
  User,
  Cat,
  ChatRoom,
  ChatMessage,
} from "@/types/dashboard";

// ─── Admin Stats ──────────────────────────────────────────────────────────────

export const ADMIN_STATS: AdminStats = {
  totalActiveBookings: 24,
  totalCatsBoarded: 24,
  cageOccupancyRate: 78,
  todayRevenue: 1_875_000,
  monthRevenue: 38_500_000,
  pendingBookings: 7,
  pendingPayments: 5,
  totalUsers: 142,
};

export const CARETAKER_STATS: CaretakerStats = {
  assignedBookings: 6,
  todayReports: 4,
  pendingReports: 2,
  emergencyAlerts: 1,
};

export const CUSTOMER_STATS: CustomerStats = {
  activeBookings: 1,
  totalCats: 2,
  totalBookings: 8,
  pendingPayments: 1,
};

export const COURIER_STATS: CourierStats = {
  todayTasks: 3,
  completedTasks: 1,
  pendingTasks: 2,
  totalCompleted: 47,
};

// ─── Bookings ─────────────────────────────────────────────────────────────────

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: "b1",
    bookingCode: "KK-20240101",
    customerId: "u3",
    customerName: "Rina Maulida",
    catId: "c1",
    catName: "Mochi",
    cageId: "k2",
    cageName: "VIP-02",
    caretakerId: "u2",
    caretakerName: "Budi Santoso",
    courierId: "u4",
    courierName: "Agus Delivery",
    services: ["VIP", "ANTAR_JEMPUT"],
    checkIn: "2024-06-15",
    checkOut: "2024-06-20",
    status: "ONGOING",
    paymentStatus: "PAID",
    totalPrice: 900_000,
    createdAt: "2024-06-12",
  },
  {
    id: "b2",
    bookingCode: "KK-20240102",
    customerId: "u5",
    customerName: "Dewi Pratiwi",
    catId: "c3",
    catName: "Luna",
    caretakerId: "u2",
    caretakerName: "Budi Santoso",
    services: ["REGULAR"],
    checkIn: "2024-06-17",
    checkOut: "2024-06-19",
    status: "APPROVED",
    paymentStatus: "PAID",
    totalPrice: 150_000,
    createdAt: "2024-06-13",
  },
  {
    id: "b3",
    bookingCode: "KK-20240103",
    customerId: "u6",
    customerName: "Hendra Wijaya",
    catId: "c4",
    catName: "Donut",
    services: ["REGULAR", "GROOMING"],
    checkIn: "2024-06-18",
    checkOut: "2024-06-21",
    status: "PENDING",
    paymentStatus: "PENDING_VERIFICATION",
    totalPrice: 285_000,
    createdAt: "2024-06-14",
  },
  {
    id: "b4",
    bookingCode: "KK-20240104",
    customerId: "u7",
    customerName: "Sari Indah",
    catId: "c5",
    catName: "Boba",
    cageId: "k1",
    cageName: "REG-05",
    caretakerId: "u2",
    caretakerName: "Budi Santoso",
    services: ["REGULAR"],
    checkIn: "2024-06-10",
    checkOut: "2024-06-15",
    status: "CHECKED_IN",
    paymentStatus: "PAID",
    totalPrice: 375_000,
    createdAt: "2024-06-09",
  },
  {
    id: "b5",
    bookingCode: "KK-20240105",
    customerId: "u8",
    customerName: "Eko Prasetyo",
    catId: "c6",
    catName: "Latte",
    services: ["VIP", "GROOMING"],
    checkIn: "2024-06-20",
    checkOut: "2024-06-25",
    status: "PENDING",
    paymentStatus: "UNPAID",
    totalPrice: 1_025_000,
    createdAt: "2024-06-15",
  },
  {
    id: "b6",
    bookingCode: "KK-20240106",
    customerId: "u3",
    customerName: "Rina Maulida",
    catId: "c2",
    catName: "Donut",
    services: ["REGULAR"],
    checkIn: "2024-06-05",
    checkOut: "2024-06-07",
    status: "COMPLETED",
    paymentStatus: "PAID",
    totalPrice: 150_000,
    createdAt: "2024-06-04",
  },
];

// ─── Cages ────────────────────────────────────────────────────────────────────

export const MOCK_CAGES: Cage[] = [
  {
    id: "k1",
    name: "REG-01",
    type: "REGULAR",
    status: "AVAILABLE",
    capacity: 1,
  },
  {
    id: "k2",
    name: "REG-02",
    type: "REGULAR",
    status: "OCCUPIED",
    capacity: 1,
    currentOccupant: "Boba",
  },
  {
    id: "k3",
    name: "REG-03",
    type: "REGULAR",
    status: "OCCUPIED",
    capacity: 1,
    currentOccupant: "Luna",
  },
  {
    id: "k4",
    name: "REG-04",
    type: "REGULAR",
    status: "MAINTENANCE",
    capacity: 1,
    notes: "Perbaikan ventilasi",
  },
  {
    id: "k5",
    name: "REG-05",
    type: "REGULAR",
    status: "AVAILABLE",
    capacity: 1,
  },
  {
    id: "k6",
    name: "VIP-01",
    type: "VIP",
    status: "OCCUPIED",
    capacity: 1,
    currentOccupant: "Mochi",
  },
  { id: "k7", name: "VIP-02", type: "VIP", status: "AVAILABLE", capacity: 1 },
  {
    id: "k8",
    name: "VIP-03",
    type: "VIP",
    status: "OCCUPIED",
    capacity: 1,
    currentOccupant: "Donut",
  },
];

// ─── Payments ─────────────────────────────────────────────────────────────────

export const MOCK_PAYMENTS: Payment[] = [
  {
    id: "p1",
    bookingId: "b1",
    bookingCode: "KK-20240101",
    customerName: "Rina Maulida",
    amount: 900_000,
    status: "PAID",
    verifiedAt: "2024-06-12",
    createdAt: "2024-06-12",
  },
  {
    id: "p2",
    bookingId: "b2",
    bookingCode: "KK-20240102",
    customerName: "Dewi Pratiwi",
    amount: 150_000,
    status: "PAID",
    verifiedAt: "2024-06-13",
    createdAt: "2024-06-13",
  },
  {
    id: "p3",
    bookingId: "b3",
    bookingCode: "KK-20240103",
    customerName: "Hendra Wijaya",
    amount: 285_000,
    status: "PENDING_VERIFICATION",
    proofUrl: "/proof.jpg",
    createdAt: "2024-06-14",
  },
  {
    id: "p4",
    bookingId: "b5",
    bookingCode: "KK-20240105",
    customerName: "Eko Prasetyo",
    amount: 1_025_000,
    status: "UNPAID",
    createdAt: "2024-06-15",
  },
  {
    id: "p5",
    bookingId: "b4",
    bookingCode: "KK-20240104",
    customerName: "Sari Indah",
    amount: 375_000,
    status: "PAID",
    verifiedAt: "2024-06-09",
    createdAt: "2024-06-09",
  },
];

// ─── Daily Reports ─────────────────────────────────────────────────────────────

export const MOCK_DAILY_REPORTS: DailyReport[] = [
  {
    id: "r1",
    bookingId: "b1",
    catName: "Mochi",
    caretakerId: "u2",
    caretakerName: "Budi Santoso",
    date: "2024-06-15",
    isEating: true,
    isDrinking: true,
    isDefecating: true,
    isUrinating: true,
    activity: "AKTIF",
    temperature: 38.5,
    notes:
      "Mochi sangat aktif hari ini, makan lahap dan bermain bola dengan semangat.",
    photos: ["/cat1.jpg", "/cat2.jpg"],
    isEmergency: false,
  },
  {
    id: "r2",
    bookingId: "b4",
    catName: "Boba",
    caretakerId: "u2",
    caretakerName: "Budi Santoso",
    date: "2024-06-15",
    isEating: false,
    isDrinking: true,
    isDefecating: false,
    isUrinating: true,
    activity: "LEMAS",
    temperature: 39.2,
    notes:
      "Boba kurang nafsu makan. Suhu sedikit di atas normal. Perlu dipantau.",
    photos: ["/cat3.jpg"],
    isEmergency: true,
  },
  {
    id: "r3",
    bookingId: "b2",
    catName: "Luna",
    caretakerId: "u2",
    caretakerName: "Budi Santoso",
    date: "2024-06-15",
    isEating: true,
    isDrinking: true,
    isDefecating: true,
    isUrinating: true,
    activity: "NORMAL",
    temperature: 38.3,
    notes: "Luna baik-baik saja, adaptasi dengan baik di kandang baru.",
    photos: ["/cat4.jpg"],
    isEmergency: false,
  },
];

// ─── Delivery Tasks ───────────────────────────────────────────────────────────

export const MOCK_DELIVERY_TASKS: DeliveryTask[] = [
  {
    id: "d1",
    bookingId: "b1",
    bookingCode: "KK-20240101",
    courierId: "u4",
    customerName: "Rina Maulida",
    customerPhone: "08123456789",
    address: "Jl. Mawar No. 12, Kel. Bunga, Kec. Taman, Kota Kendari",
    catName: "Mochi",
    type: "PICKUP",
    scheduledAt: "2024-06-15 09:00",
    status: "SAMPAI_TUJUAN",
    notes: "Kucing dalam carrier merah",
  },
  {
    id: "d2",
    bookingId: "b7",
    bookingCode: "KK-20240107",
    courierId: "u4",
    customerName: "Fajar Nugroho",
    customerPhone: "08567891234",
    address: "Jl. Kenanga No. 5, Kel. Melati, Kec. Pusat, Kota Kendari",
    catName: "Ciko",
    type: "DELIVERY",
    scheduledAt: "2024-06-15 14:00",
    status: "DALAM_PERJALANAN",
    notes: "Antar ke alamat ibu",
  },
  {
    id: "d3",
    bookingId: "b8",
    bookingCode: "KK-20240108",
    courierId: "u4",
    customerName: "Maya Sari",
    customerPhone: "08234567890",
    address: "Perum. Griya Indah Blok B No. 7, Kota Kendari",
    catName: "Whiskey",
    type: "PICKUP",
    scheduledAt: "2024-06-15 16:00",
    status: "MENUJU_LOKASI",
  },
];

// ─── Users ────────────────────────────────────────────────────────────────────

export const MOCK_USERS: User[] = [
  {
    id: "u1",
    name: "Admin KucingKu",
    email: "admin@kucingku.id",
    phone: "081200000001",
    role: "ADMIN",
    isActive: true,
    createdAt: "2024-01-01",
  },
  {
    id: "u2",
    name: "Budi Santoso",
    email: "budi@kucingku.id",
    phone: "081200000002",
    role: "CARETAKER",
    isActive: true,
    createdAt: "2024-01-15",
  },
  {
    id: "u3",
    name: "Rina Maulida",
    email: "rina@email.com",
    phone: "081200000003",
    role: "CUSTOMER",
    isActive: true,
    createdAt: "2024-02-01",
  },
  {
    id: "u4",
    name: "Agus Delivery",
    email: "agus@kucingku.id",
    phone: "081200000004",
    role: "COURIER",
    isActive: true,
    createdAt: "2024-02-10",
  },
  {
    id: "u5",
    name: "Dewi Pratiwi",
    email: "dewi@email.com",
    phone: "081200000005",
    role: "CUSTOMER",
    isActive: true,
    createdAt: "2024-03-01",
  },
  {
    id: "u6",
    name: "Hendra Wijaya",
    email: "hendra@email.com",
    phone: "081200000006",
    role: "CUSTOMER",
    isActive: false,
    createdAt: "2024-03-15",
  },
  {
    id: "u7",
    name: "Sari Indah",
    email: "sari@email.com",
    phone: "081200000007",
    role: "CUSTOMER",
    isActive: true,
    createdAt: "2024-04-01",
  },
  {
    id: "u8",
    name: "Eko Prasetyo",
    email: "eko@email.com",
    phone: "081200000008",
    role: "CUSTOMER",
    isActive: true,
    createdAt: "2024-04-20",
  },
];

// ─── Cats ─────────────────────────────────────────────────────────────────────

export const MOCK_CATS: Cat[] = [
  {
    id: "c1",
    ownerId: "u3",
    name: "Mochi",
    ras: "Scottish Fold",
    age: 2,
    weight: 3.5,
    vaccinationStatus: true,
    vaccinationExpiry: "2025-06-01",
    diseaseHistory: "Pernah flu ringan (2023)",
    notes: "Suka tuna, takut suara keras",
  },
  {
    id: "c2",
    ownerId: "u3",
    name: "Donut",
    ras: "Domestic Shorthair",
    age: 1,
    weight: 2.8,
    vaccinationStatus: true,
    vaccinationExpiry: "2025-03-15",
    diseaseHistory: "-",
    notes: "Aktif dan suka bermain",
  },
];

// ─── Chat ─────────────────────────────────────────────────────────────────────

export const MOCK_CHAT_ROOMS: ChatRoom[] = [
  {
    id: "cr1",
    customerId: "u3",
    customerName: "Rina Maulida",
    lastMessage: "Terima kasih, Mochi sudah makan?",
    lastMessageAt: "2024-06-15 10:30",
    unreadCount: 2,
  },
  {
    id: "cr2",
    customerId: "u5",
    customerName: "Dewi Pratiwi",
    lastMessage: "Ok siap, besok jam berapa?",
    lastMessageAt: "2024-06-14 16:00",
    unreadCount: 0,
  },
  {
    id: "cr3",
    customerId: "u7",
    customerName: "Sari Indah",
    lastMessage: "Foto terbarunya dong 😊",
    lastMessageAt: "2024-06-15 09:15",
    unreadCount: 1,
  },
];

export const MOCK_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: "m1",
    roomId: "cr1",
    senderId: "u3",
    senderName: "Rina Maulida",
    senderRole: "CUSTOMER",
    message: "Halo, bagaimana kondisi Mochi hari ini?",
    sentAt: "2024-06-15 10:00",
    isRead: true,
  },
  {
    id: "m2",
    roomId: "cr1",
    senderId: "u1",
    senderName: "Admin KucingKu",
    senderRole: "ADMIN",
    message:
      "Halo Kak Rina! Mochi baik-baik saja, aktif dan makan dengan lahap 😸",
    sentAt: "2024-06-15 10:15",
    isRead: true,
  },
  {
    id: "m3",
    roomId: "cr1",
    senderId: "u3",
    senderName: "Rina Maulida",
    senderRole: "CUSTOMER",
    message: "Terima kasih, Mochi sudah makan?",
    sentAt: "2024-06-15 10:30",
    isRead: false,
  },
];

// ─── Revenue Chart Data ───────────────────────────────────────────────────────

export const REVENUE_DATA = [
  { month: "Jan", revenue: 24_500_000 },
  { month: "Feb", revenue: 28_200_000 },
  { month: "Mar", revenue: 32_100_000 },
  { month: "Apr", revenue: 29_800_000 },
  { month: "Mei", revenue: 35_400_000 },
  { month: "Jun", revenue: 38_500_000 },
];
